# server
server:
  port: 80
# spring
spring:
  # application
  application:
    name: gateway
  # spring cloud
  cloud:
    # spring cloud gateway
    gateway:
      routes:
      - id: email_host
        uri: http://www.163.com
        predicates:
        - Path=/email
      discovery:
        locator:
          # 开启通过eureka中的service id进行路由
          enabled: true
          # 开启支持service id小写（spring.application.name中不能有下划线）
          lower-case-service-id: true
# eureka
eureka:
  # eureka client
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    com.lshaci: info
