# server
server:
  port: 80
# spring
spring:
  # spring cloud
  cloud:
    # spring cloud gateway
    gateway:
      routes:
      - id: host_route
        uri: http://example.org
        predicates:
        - Path=/foo/**
# eureka
eureka:
  # eureka client
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    com.lshaci: info
